services:
  base:
    image: base
    build: .
  build:
    image: base
    depends_on:
      - base
    volumes:
      - ./frontend:/aw-rss/frontend:ro
      - ./dist:/aw-rss/dist:rw
    command: npm run prod
  sandbox:
    image: base
    depends_on:
      - base
    volumes:
      - ./frontend:/aw-rss/frontend:ro
      - ./dist:/aw-rss/dist:rw
    command: bash
  copy-modules:
    image: base
    depends_on:
      - base
    volumes:
      - ./frontend:/aw-rss/frontend:ro
      - ./node_modules:/aw-rss/node_modules_out:rw
      - ./package.json:/aw-rss/parent-package.json:rw
      - ./package-lock.json:/aw-rss/parent-lock.json:rw
    command: sh -c "rsync -rlptD --delete --size-only node_modules/ node_modules_out; cp package.json parent-package.json; cp package-lock.json parent-lock.json"
