services:
  aw-rss-base:
    image: aw-rss-base
    build: .
  build:
    image: aw-rss-base
    depends_on:
      - aw-rss-base
    volumes:
      - ./frontend:/aw-rss/frontend:ro
      - ./dist:/aw-rss/parent-dist:rw
    command: sh -c 'npm run prod && rm -rf parent-dist/* && cp -r dist/* parent-dist/'
  sandbox:
    image: aw-rss-base
    depends_on:
      - aw-rss-base
    volumes:
      - ./frontend:/aw-rss/frontend:ro
      - ./dist:/aw-rss/parent-dist:rw
      - ./package.json:/aw-rss/parent-package.json:rw
      - ./package-lock.json:/aw-rss/parent-lock.json:rw
    command: bash
  copy-modules:
    image: aw-rss-base
    depends_on:
      - aw-rss-base
    volumes:
      - ./frontend:/aw-rss/frontend:ro
      - ./node_modules:/aw-rss/node_modules_out:rw
    command: sh -c "rsync -rlptD --delete --size-only node_modules/ node_modules_out"
